version: '3.7'

services:
  shard:
    build:
      context: clouduo
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:${SHARD_PORT}:${SHARD_PORT}"
    volumes:
      - ./shard:/shard
      - ./client:/client
    restart: "unless-stopped"
    env_file:
      - .env