services:

  clouduo:
    build:
      context: ./clouduo/build
      dockerfile: Dockerfile
      args:
        - OWNER_USERNAME=${OWNER_USERNAME}
        - OWNER_PASSWORD=${OWNER_PASSWORD}
        - SHARD_NAME=${SHARD_NAME}
        - SHARD_PORT=${SHARD_PORT}
    image: clouduo:latest
    volumes:
      - ./data/saves:/shard/Saves
      - ./data/backups:/shard/Backups
      - ./data/mods:/shard/Scripts/Custom/CloudUO/Mods
    ports:
      - 127.0.0.1:${SHARD_PORT}:2593
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - clouduo

networks:
  clouduo:
    external: true
