version: '3.7'

services:

  shard:
    image: clouduo:latest
    container_name: ${SHARD_TAG}
    volumes:
      - ../../client:/client
      - saves:/shard/Saves
      - ./config:/shard/Config
      - ./scripts/Custom:/shard/Scripts/Custom
    ports:
      - 127.0.0.1:${SHARD_PORT}:2593
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - clouduo

  mysql:
    image: mariadb:latest
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql

volumes:
  saves:

networks:
  clouduo:
    external: true
