version: '3.7'

services:
  shard:
    image: clouduo:latest
    container_name: ${SHARD_TAG}
    volumes:
      - ../../client:/client
      - saves:/shard/Saves
      - ./Scripts/Custom:/shard/Scripts/Custom
    ports:
      - 127.0.0.1:${SHARD_PORT}:2593
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - clouduo

volumes:
  saves:
  
networks:
  clouduo:
    external: true
